# ansible-playbook update.yml --check --this will go through the motions of the playbook but doesnt actually install/update anything
# ansible-playbook update.yml --check --diff --this shows before and after differences for files/config
# ansible-playbook update.yml --syntax-check --this will check for any errors in a playbook
---
- name: Daily package updates
  hosts: all
  become: yes
  tasks:
    - name: Update apt package cache (Debian/Ubuntu)
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"

    - name: Update all packages (RHEL/CentOS/Rocky)
      dnf:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"
