---
- name: Daily security baseline check
  hosts: all
  become: yes
  tasks:
    - name: Ensure SSH service is running
      service:
        name: ssh
        state: started
      when: ansible_os_family == "Debian"

    - name: Ensure SSHD service is running
      service:
        name: sshd
        state: started
      when: ansible_os_family == "RedHat"

    - name: Check sudoers file
      command: visudo -c
      register: sudo_check
      failed_when: sudo_check.rc != 0

    - debug:
        var: sudo_check.stdout_lines
